### PR TITLE
add render async method to support making async calls

### PR DESCRIPTION
**Pull request by chuck-waters**
This just adds an async render method to make it easier for calling async methods while using the framework.

### CODE REVIEW

**Comment by kapi2289** [comment]
Hi! Can you please give some example of usage, when it is necessary? This function is sync, and it just creates a new object of `Response`.

**Comment by chuck-waters** [comment]
Well any time you have to make async calls from your controller action/method, the whole method has to be async. And adding this small change allows it to just be supported out of the box. Otherwise you will have to wrap your return object, the inertia render method, in an inline async call that executes it synchronously.

I did find that if I change my return types to IActionResult though, this isn't needed. At the time I submitted the Merge I was wrapping the return calls. So if you'd rather not add it, there is a work around already.

**Comment by kapi2289** [comment]
That makes sense, we can add the `RenderAsync` method, preserving backwards compatibility. If you now have an idea how to do it better instead of wrapping it, you can make a commit with this change. Also, please remove from git the folder `.vs`.

**Comment by chuck-waters** [comment]
ah, just to clarify, I meant that if the controller method itself returns IActionResult, the renderAsync isn't needed. But if for whatever reason that's not what gets returned it could be needed still. 

Honestly, the project I'm using this on currently, I've gone back to the regular Render method. I could see some still needed the RenderAsync, but it's no longer needed for what I'm now doing. I'll at least remove the .vs folder and then let you decide either way.

Thanks for the feedback, I appreciate you getting back to me.

**Comment by chuck-waters** [comment]
Removed the .vs folder from the merge.

**Comment by kapi2289** [comment]
Thanks, I'll test it before merging in a project to see how it works using `IActionResult` and decide whether this method is necessary.

**Comment by kapi2289** [comment]
I've just checked it and the problem was totally different. It doesn't matter if the method is async or not, the `Inertia.Render` returns custom `Response` class which implements `IActionResult` interface. If you set your controller function return type to `ActionResult`, it returns error because `Response` doesn't extend `ActionResult`.

If you have further questions, don't hesitate to ask. Anyway, thanks for your PR!

**Pull request closed without merging**
